### ISSUE TITLE
You can use JS arrays in Jolf

### ISSUE THREAD

**Issue by RikerW** [ConorOBrien-Foxx/Jolf#8]
Mostly just to point this out for other yelling people.

**Comment by RikerW** [comment]
You can tag this wontfix and close it.

**Comment by ConorOBrien-Foxx** [comment]
uhhh why is this a problem?

**Comment by RikerW** [comment]
Did you not read the second message.

On Mon, Apr 25, 2016 at 12:26 PM, ConorOBrien-Foxx <notifications@github.com

**Comment by phase** [comment]
Don't make issues about features.
