### ISSUE TITLE
Interpreter does not do anything

### ISSUE THREAD

**Issue by ETHproductions** [ConorOBrien-Foxx/Jolf#9]
I've tried the interpreter on both Firefox and Chrome, and on both, the interpreter has no functionality whatsoever. On page load, the following error appears in both browsers' consoles:

```
Uncaught ReferenceError: loadWordList is not defined
```

I wanted to use Jolf for a nested-programs entry, but I can't right now because of this bug. :(

**Comment by ETHproductions** [comment]
The error appears to be caused by [this line](https://github.com/ConorOBrien-Foxx/Jolf/blob/gh-pages/index.html#L19):

```
    setTimeout(loadWordList, 2000);
```

Is `loadWordList` supposed to be defined by one of the external scripts?

**Comment by ETHproductions** [comment]
I forked and commented out that line, and it seems to work perfectly: https://ethproductions.github.io/Jolf

**Comment by ConorOBrien-Foxx** [comment]
That line obtains the word list. It should be in the JS file or the HTML file. Can't fix until I get home.
